import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import MessageModal from "@/components/MessageModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Qtec Blog",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StoreProvider>
					<MessageModal />
					{children}
				</StoreProvider>
			</body>
		</html>
	);
}
